### ISSUE TITLE
Add way to add env variables during runtime

### ISSUE THREAD

**Issue by frkam** [youtogether-online/frontend#5]
Now vite doesn't support adding env variables during runtime, but without that feature we cannot add env variables while creating docker container.

Related issues:
https://github.com/sveltejs/kit/issues/3004

**Comment by frkam** [comment]
Related thread:
https://laracasts.com/discuss/channels/vite/change-environment-variables-at-runtime-react-vite-with-docker-and-nginx

**Comment by Skulrag** [comment]
Hi,

A solution for me was to follow this tutorial that explain how to use dynamic variable via a built-in module :

https://joyofcode.xyz/sveltekit-environment-variables

I added this import on my server files :
`import { env } from '$env/dynamic/private'`

After that I can use my env var like this : 

`console.log(env.MY_VAR)`

My problem was not been able to use docker compose env var ! It solved it.

**Comment by lucasmgsilva** [comment]
> Hi,
> 
> A solution for me was to follow this tutorial that explain how to use dynamic variable via a built-in module :
> 
> https://joyofcode.xyz/sveltekit-environment-variables
> 
> I added this import on my server files : `import { env } from '$env/dynamic/private'`
> 
> After that I can use my env var like this :
> 
> `console.log(env.MY_VAR)`
> 
> My problem was not been able to use docker compose env var ! It solved it.

Any alternatives to React with Vite?

**Comment by ghost** [comment]
> > Hi,
> > A solution for me was to follow this tutorial that explain how to use dynamic variable via a built-in module :
> > https://joyofcode.xyz/sveltekit-environment-variables
> > I added this import on my server files : `import { env } from '$env/dynamic/private'`
> > After that I can use my env var like this :
> > `console.log(env.MY_VAR)`
> > My problem was not been able to use docker compose env var ! It solved it.
> 
> Any alternatives to React with Vite?

In this project i used import-meta-env. great tool! you can see project example in this repository
